### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by dust-shadows**
I noticed that the title of the configuration screen was not translated, so I made a small change in the lang file.
Great Mod!

### CODE REVIEW

**Comment by Kurisu-Null** [comment]
Thanks for your contribution and kind feedback! Is it also possible to add those to all other branches via the pr :D?

**Comment by dust-shadows** [comment]
> @dust-shadows Thanks for your contribution and kind feedback! Is it also possible to add those to all other branches via the pr :D?

Sure! I'll finish it later.

**Comment by Kurisu-Null** [comment]
@dust-shadows I alrdy did and released! Thanks

**Comment by dust-shadows** [comment]
> @dust-shadows I alrdy did and released! Thanks

OK

**Comment by dust-shadows** [comment]
@Kurisu-Null What is the function of "Falling distance multiplier"? I want to make sure I understand and translate it correctly, thanks.

**Pull request merged**
